# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jftcv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferences',
            name='order',
        ),
        migrations.RemoveField(
            model_name='education',
            name='order',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='order',
        ),
        migrations.AddField(
            model_name='conferences',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
