# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jftcv', '0003_personaldata_initials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='conferences',
            name='owner',
            field=models.CharField(default='Javier Fernández Troncoso', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='owner',
            field=models.CharField(default='Javier Fernández Troncoso', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='owner',
            field=models.CharField(default='Javier Fernández Troncoso', max_length=50),
            preserve_default=False,
        ),
    ]
