# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jftcv', '0004_auto_20170308_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='certificate',
        ),
    ]
