# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jftcv', '0005_remove_workexperience_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('writen', models.CharField(max_length=10)),
                ('spoken', models.CharField(max_length=10)),
                ('understood', models.CharField(max_length=10)),
                ('native', models.CharField(max_length=10)),
            ],
        ),
    ]
