# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jftcv', '0006_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languages',
            old_name='writen',
            new_name='written',
        ),
    ]
