# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jftcv', '0007_auto_20170308_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigComps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('comp', models.CharField(max_length=50)),
                ('infoprocessing', models.CharField(max_length=10)),
                ('contentcreation', models.CharField(max_length=10)),
                ('safety', models.CharField(max_length=10)),
                ('problemsolving', models.CharField(max_length=10)),
            ],
        ),
    ]
