# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jftcv', '0009_personaldata_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferences',
            options={'verbose_name_plural': 'Conferences and events'},
        ),
        migrations.AlterModelOptions(
            name='digcomps',
            options={'verbose_name_plural': 'Digital competences'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'Trainings'},
        ),
        migrations.AlterModelOptions(
            name='languages',
            options={'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='personaldata',
            options={'verbose_name_plural': 'Personal data'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name_plural': 'Work experiences'},
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='id',
        ),
        migrations.AlterField(
            model_name='conferences',
            name='owner',
            field=models.CharField(max_length=50, verbose_name='User (full name)'),
        ),
        migrations.AlterField(
            model_name='digcomps',
            name='comp',
            field=models.CharField(max_length=50, verbose_name='Digital competence'),
        ),
        migrations.AlterField(
            model_name='digcomps',
            name='contentcreation',
            field=models.CharField(max_length=10, verbose_name='Content creation (level)'),
        ),
        migrations.AlterField(
            model_name='digcomps',
            name='infoprocessing',
            field=models.CharField(max_length=10, verbose_name='Information processing (level)'),
        ),
        migrations.AlterField(
            model_name='digcomps',
            name='owner',
            field=models.CharField(max_length=50, verbose_name='User (full name)'),
        ),
        migrations.AlterField(
            model_name='digcomps',
            name='problemsolving',
            field=models.CharField(max_length=10, verbose_name='Problem solving (level)'),
        ),
        migrations.AlterField(
            model_name='digcomps',
            name='safety',
            field=models.CharField(max_length=10, verbose_name='Safety (level)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='owner',
            field=models.CharField(max_length=50, verbose_name='User (full name)'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='language',
            field=models.CharField(max_length=50, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='native',
            field=models.CharField(max_length=10, verbose_name='Native language (Yes/No)'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='owner',
            field=models.CharField(max_length=50, verbose_name='User (full name)'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='spoken',
            field=models.CharField(max_length=10, verbose_name='Spoken (level)'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='understood',
            field=models.CharField(max_length=10, verbose_name='Understood (level)'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='written',
            field=models.CharField(max_length=10, verbose_name='Written (level)'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='initials',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='filename',
            field=models.CharField(max_length=50, verbose_name='Folder (inside the django application)'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='language',
            field=models.CharField(max_length=50, verbose_name='Programming language'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Project name'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='owner',
            field=models.CharField(max_length=50, verbose_name='User (full name)'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='owner',
            field=models.CharField(max_length=50, verbose_name='User (full name)'),
        ),
    ]
