# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jftcv', '0011_router'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='owner',
            field=models.CharField(default='jft', max_length=50, verbose_name='user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conferences',
            name='owner',
            field=models.CharField(max_length=50, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='digcomps',
            name='owner',
            field=models.CharField(max_length=50, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='education',
            name='owner',
            field=models.CharField(max_length=50, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='owner',
            field=models.CharField(max_length=50, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='owner',
            field=models.CharField(max_length=50, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='owner',
            field=models.CharField(max_length=50, verbose_name='user'),
        ),
    ]
