# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jftcv', '0012_auto_20170309_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
