# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jftcv', '0013_router_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50, verbose_name='user')),
                ('specifications', models.FileField(upload_to='router_specifications', verbose_name='Picture (the name must match the initials of the user')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
