# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jftcv', '0014_imgprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgprofile',
            name='specifications',
            field=models.FileField(upload_to='', verbose_name='Picture (the name must match the initials of the user. png format'),
        ),
    ]
