# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jftcv', '0015_auto_20170310_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imgprofile',
            options={'verbose_name_plural': 'Profile image'},
        ),
        migrations.AlterModelOptions(
            name='router',
            options={'verbose_name_plural': 'CV file'},
        ),
    ]
