# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jftcv', '0016_auto_20170310_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='conferences',
            name='description',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='education',
            name='certificate',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='imgprofile',
            name='specifications',
            field=models.FileField(upload_to='', verbose_name='Picture (.png)'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='profile',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='projects',
            name='filename',
            field=models.CharField(blank=True, max_length=50, verbose_name='Folder (inside the django application)'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
