# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jftcv', '0017_auto_20170310_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='country',
            field=models.CharField(max_length=30),
        ),
    ]
