# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jftcv', '0018_auto_20170310_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='profile',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
